// examples/react/src/App.tsx
import { useEffect, useRef, useState } from 'react'
/*
 * Web Component Import:
 * Importing the blocks-graph library automatically registers
 * the 'blocks-graph' custom element globally.
 */
import '@lumina-study/blocks-graph'
import './App.css'

/**
 * TypeScript Type Definition for Web Component:
 * Defines the custom element interface with imperative API methods
 * and properties for type-safe access via React ref
 */
interface BlocksGraphElement extends HTMLElement {
  loadFromJson: (json: string, version: 'v0.1') => void
  language: string
  showPrerequisites: boolean
  showParents: boolean
}

function App() {
  /*
   * Type-Safe Ref for Web Component:
   * useRef hook provides access to the Web Component instance
   * Typed with custom interface for imperative API access
   */
  const graphRef = useRef<BlocksGraphElement>(null)

  // State management for interactive controls
  const [language, setLanguage] = useState<'en' | 'he'>('en')
  const [showPrerequisites, setShowPrerequisites] = useState(true)
  const [showParents, setShowParents] = useState(true)
  const [status, setStatus] = useState('Ready to load data')
  const [selectedBlock, setSelectedBlock] = useState<string | null>(null)

  /**
   * Data Loading Lifecycle:
   * useEffect hook loads sample data when component mounts
   * Empty dependency array ensures this runs only once
   */
  useEffect(() => {
    const loadData = async () => {
      try {
        setStatus('Loading data...')

        /*
         * Fetch data from The Open University Combinatorics course
         * This demonstrates loading data from a remote URL
         */
        const response = await fetch(
          'https://raw.githubusercontent.com/luminastudy/the-open-university-combinatorics/refs/heads/main/lumina.json'
        )

        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`)
        }

        const blocks = await response.json()

        /*
         * Call loadFromJson on Web Component instance via ref
         * This is the imperative API for loading data
         */
        if (graphRef.current) {
          graphRef.current.loadFromJson(JSON.stringify(blocks), 'v0.1')
          setStatus(`Loaded ${blocks.length} blocks successfully`)
        }
      } catch (error) {
        console.error('Error loading data:', error)
        setStatus(
          `Error loading data: ${
            error instanceof Error ? error.message : 'Unknown error'
          }`
        )
      }
    }

    loadData()
  }, []) // Run only on mount

  /**
   * Attribute Synchronization:
   * useEffect hooks to keep Web Component attributes in sync with React state
   * This demonstrates how to update Web Component properties from React
   */
  useEffect(() => {
    if (graphRef.current) {
      graphRef.current.language = language
    }
  }, [language])

  useEffect(() => {
    if (graphRef.current) {
      graphRef.current.showPrerequisites = showPrerequisites
    }
  }, [showPrerequisites])

  useEffect(() => {
    if (graphRef.current) {
      graphRef.current.showParents = showParents
    }
  }, [showParents])

  /**
   * Event Listener Registration:
   * useEffect hook to register Web Component event listeners
   * Cleanup function removes listeners when component unmounts
   */
  useEffect(() => {
    const graph = graphRef.current
    if (!graph) return

    // Handle blocks-rendered event
    const handleBlocksRendered = (event: Event) => {
      const customEvent = event as CustomEvent
      console.log('Blocks rendered:', customEvent.detail)
      if (customEvent.detail?.blockCount !== undefined) {
        setStatus(`Rendered ${customEvent.detail.blockCount} blocks`)
      }
    }

    // Handle block-selected event
    const handleBlockSelected = (event: Event) => {
      const customEvent = event as CustomEvent
      console.log('Block selected:', customEvent.detail)
      if (customEvent.detail?.blockId) {
        setSelectedBlock(customEvent.detail.blockId)
        const levelText =
          customEvent.detail.selectionLevel === 0
            ? 'default view'
            : customEvent.detail.selectionLevel === 1
              ? 'showing graph'
              : 'showing graph + sub-blocks'
        setStatus(`Selected block - ${levelText}`)
      } else {
        setSelectedBlock(null)
        setStatus('Selection cleared')
      }
    }

    // Add event listeners
    graph.addEventListener('blocks-rendered', handleBlocksRendered)
    graph.addEventListener('block-selected', handleBlockSelected)

    // Cleanup: remove event listeners when component unmounts
    return () => {
      graph.removeEventListener('blocks-rendered', handleBlocksRendered)
      graph.removeEventListener('block-selected', handleBlockSelected)
    }
  }, []) // Run only on mount/unmount

  return (
    <div className="app">
      <header className="header">
        <h1>@lumina-study/blocks-graph</h1>
        <p>The Open University - Combinatorics Course</p>
      </header>

      {/* Interactive Controls Panel */}
      <div className="controls">
        <div className="control-group">
          <label htmlFor="language-select">Language:</label>
          <select
            id="language-select"
            value={language}
            onChange={e => setLanguage(e.target.value as 'en' | 'he')}
          >
            <option value="en">English</option>
            <option value="he">Hebrew (עברית)</option>
          </select>
        </div>

        <div className="control-group checkbox">
          <label>
            <input
              type="checkbox"
              checked={showPrerequisites}
              onChange={e => setShowPrerequisites(e.target.checked)}
            />
            Show Prerequisites
          </label>
        </div>

        <div className="control-group checkbox">
          <label>
            <input
              type="checkbox"
              checked={showParents}
              onChange={e => setShowParents(e.target.checked)}
            />
            Show Parents
          </label>
        </div>
      </div>

      {/* Web Component Integration */}
      <div className="graph-container">
        {/*
          Rendering Web Component in React:
          - ref prop connects to useRef hook for imperative API access
          - HTML attributes are passed as props
          - Inline styles can be applied via the style prop
        */}
        <blocks-graph
          ref={graphRef}
          language={language}
          show-prerequisites={showPrerequisites ? 'true' : 'false'}
          show-parents={showParents ? 'true' : 'false'}
          style={{
            width: '100%',
            height: '600px',
            display: 'block',
          }}
        />
      </div>

      {/* Info Panel */}
      <div className="info-panel">
        <h3>How to Use This Example</h3>
        <ul>
          <li>Click on blocks to explore their relationships</li>
          <li>
            Use the language selector to switch between English and Hebrew
          </li>
          <li>Toggle checkboxes to show/hide relationships</li>
          <li>Observe how React state updates the Web Component</li>
          <li>Check the browser console for event logs</li>
        </ul>
        <div className="status">
          <strong>Status:</strong> {status}
        </div>
        {selectedBlock && (
          <div className="selected-block">
            <strong>Selected Block ID:</strong> {selectedBlock.substring(0, 8)}
            ...
          </div>
        )}
      </div>
    </div>
  )
}

export default App

// examples/angular/src/app/app.component.ts
import {
  Component,
  OnInit,
  AfterViewInit,
  ViewChild,
  ElementRef,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
// Import the web component registration
import '@lumina-study/blocks-graph'
import type { BlocksGraph } from '@lumina-study/blocks-graph'

interface BlockSchemaV01 {
  id: string
  title: { he_text: string; en_text: string }
  prerequisites: string[]
  parents: string[]
}

interface BlocksRenderedDetail {
  blockCount: number
}

interface BlockSelectedDetail {
  blockId: string | null
  selectionLevel: number
  navigationStack: string[]
}

/**
 * Angular Example Using the Web Component Directly
 *
 * This demonstrates using the <blocks-graph> web component with
 * CUSTOM_ELEMENTS_SCHEMA and ViewChild for direct access.
 */
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit, AfterViewInit {
  @ViewChild('graphElement') graphElement?: ElementRef<BlocksGraph>

  // State management
  blocks: BlockSchemaV01[] | null
  language: 'en' | 'he'
  orientation: 'ttb' | 'ltr' | 'rtl' | 'btt'
  showPrerequisites: boolean
  status: string
  selectedBlock: string | null

  constructor() {
    this.blocks = null
    this.language = 'en'
    this.orientation = 'ttb'
    this.showPrerequisites = true
    this.status = 'Loading data...'
    this.selectedBlock = null
  }

  ngOnInit() {
    this.loadData()
  }

  ngAfterViewInit() {
    this.setupEventListeners()
  }

  private async loadData() {
    try {
      const response = await fetch(
        'https://raw.githubusercontent.com/luminastudy/the-open-university-combinatorics/refs/heads/main/lumina.json'
      )

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      const data = await response.json()
      this.blocks = data
      this.status = `Loaded ${data.length} blocks successfully`

      // Load blocks into the web component after data is ready
      setTimeout(() => this.updateGraph(), 0)
    } catch (error) {
      console.error('Error loading data:', error)
      this.status = `Error: ${error instanceof Error ? error.message : 'Unknown error'}`
    }
  }

  private setupEventListeners() {
    if (!this.graphElement) return
    const element = this.graphElement.nativeElement
    if (!element) return

    element.addEventListener('blocks-rendered', (event: Event) => {
      const customEvent = event as CustomEvent<BlocksRenderedDetail>
      console.log('Blocks rendered:', customEvent.detail)
      this.status = `Rendered ${customEvent.detail.blockCount} blocks`
    })

    element.addEventListener('block-selected', (event: Event) => {
      const customEvent = event as CustomEvent<BlockSelectedDetail>
      console.log('Block selected:', customEvent.detail)
      if (customEvent.detail.blockId) {
        this.selectedBlock = customEvent.detail.blockId
        const levelText =
          customEvent.detail.selectionLevel === 0
            ? 'default view'
            : customEvent.detail.selectionLevel === 1
              ? 'showing graph'
              : 'showing graph + sub-blocks'
        this.status = `Selected block - ${levelText}`
      } else {
        this.selectedBlock = null
        this.status = 'Selection cleared'
      }
    })
  }

  updateGraph() {
    if (!this.graphElement) return
    const element = this.graphElement.nativeElement
    if (!element || !this.blocks) return

    // Set attributes
    element.setAttribute('language', this.language)
    element.setAttribute('orientation', this.orientation)
    element.setAttribute('show-prerequisites', String(this.showPrerequisites))

    // Load blocks
    element.loadFromJson(JSON.stringify(this.blocks), 'v0.1')
  }

  onLanguageChange() {
    this.updateGraph()
  }

  onOrientationChange() {
    this.updateGraph()
  }

  onShowPrerequisitesChange() {
    this.updateGraph()
  }
}

<div class="app">
  <header class="header">
    <h1>&#64;lumina-study/blocks-graph</h1>
    <p *ngIf="!blocks">Loading data...</p>
    <ng-container *ngIf="blocks">
      <p>The Open University - Combinatorics Course</p>
      <small>Using Web Component with CUSTOM_ELEMENTS_SCHEMA</small>
    </ng-container>
  </header>

  <!-- Loading State -->
  <div *ngIf="!blocks" class="info-panel">
    <p>{{ status }}</p>
  </div>

  <!-- Main Content -->
  <ng-container *ngIf="blocks">
    <!-- Interactive Controls Panel -->
    <div class="controls">
      <div class="control-group">
        <label for="language-select">Language:</label>
        <select id="language-select" [(ngModel)]="language" (ngModelChange)="onLanguageChange()">
          <option value="en">English</option>
          <option value="he">Hebrew</option>
        </select>
      </div>

      <div class="control-group">
        <label for="orientation-select">Orientation:</label>
        <select id="orientation-select" [(ngModel)]="orientation" (ngModelChange)="onOrientationChange()">
          <option value="ttb">Top to Bottom</option>
          <option value="ltr">Left to Right</option>
          <option value="rtl">Right to Left</option>
          <option value="btt">Bottom to Top</option>
        </select>
      </div>

      <div class="control-group checkbox">
        <label>
          <input type="checkbox" [(ngModel)]="showPrerequisites" (ngModelChange)="onShowPrerequisitesChange()" />
          Show Prerequisites
        </label>
      </div>
    </div>

    <!-- Web Component with ViewChild access -->
    <div class="graph-container">
      <blocks-graph
        #graphElement
        [attr.language]="language"
        [attr.orientation]="orientation"
        [attr.show-prerequisites]="showPrerequisites"
        style="width: 100%; height: 600px; display: block;"
      ></blocks-graph>
    </div>

    <!-- Info Panel -->
    <div class="info-panel">
      <h3>Web Component Integration</h3>
      <ul>
        <li>Uses CUSTOM_ELEMENTS_SCHEMA for web component support</li>
        <li>ViewChild for direct element access</li>
        <li>Event listeners for blocks-rendered and block-selected</li>
        <li>Works with any web component</li>
      </ul>
      <div class="status">
        <strong>Status:</strong> {{ status }}
      </div>
      <div *ngIf="selectedBlock" class="selected-block">
        <strong>Selected Block ID:</strong> {{ selectedBlock.substring(0, 8) }}...
      </div>
    </div>
  </ng-container>
</div>
